version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moderaitor
  moderaitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    secrets:
      - HUGGINGFACEHUB_API_TOKEN
      - praw_client_secret
      - praw_client_id
    environment:
      - SECRETS_PATH
      - COMMENTS_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

secrets:
  HUGGINGFACEHUB_API_TOKEN:
    file: docker/HUGGINGFACEHUB_API_TOKEN.secret
  praw_client_secret:
    file: docker/praw_client_secret.secret
  praw_client_id:
    file: docker/praw_client_id.secret
